# 串口配置
serial_config:
  port_name: "/dev/ttyUSB0"  # Linux: /dev/ttyUSB0, Windows: COMx
  baudrate: 115200           # 波特率
  retry_times: 3             # 重传次数（容错）
  timeout_ms: 1000           # 通信超时（ms）
  crc_check: true            # 是否开启CRC校验

# 其他配置不变...
camera_config:
  camera_index: 0            # 相机设备索引
  width: 1280                # 图像宽度
  height: 720                # 图像高度
  fps: 30                    # 帧率
camera_matrix: [2479.79773265868, 0, 624.843541232562, 0, 2478.98595904058, 516.678095396654, 0, 0, 1]
dist_coeffs: [-0.0896322190932089, 0.486000473389527, 0, 0, 0]

aruco_config:
  dict_id: "DICT_6X6_250"
  marker_size: 0.12           #单位m，同下

gimbal_config:
  position_in_cam: [0.0, 0.0, 0.91]
  loop_delay_ms: 30